---
# tasks file for parallel

- name: Install {{ web_packages }}
  yum:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ web_packages }}"
  when: inventory_hostname in groups ["webservers"]

- name: Install {{ fw_packages }}
  yum:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ fw_packages }}"

- name: Install {{ lb_packages }}
  yum:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ lb_packages }}"
  when: inventory_hostname in groups ["lbserver"]

- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true
  when: inventory_hostname in groups ["webservers"]

- name: Start and enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: true 

- name: Start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: true
  when: inventory_hostname in groups ["lbserver"]

- name: enalbe port 80/tcp on all servers
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: copy index template file
  template:
    src: old_index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname in groups ["webservers"]
  notify: restart httpd

- name: HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy
    mode: 0644
  when: inventory_hostname in groups ["lbserver"]
  notify: restart haproxy






